export type User = {
    id: string;
    name: string;
    role: "organizer" | "judge" | "participant";
};
export const users: User[] = [
    { id: "u1", name: "Mohit Jeswani", role: "participant" },
    { id: "u2", name: "Michael Magan", role: "judge" },
    { id: "u3", name: "Kunal Kushwaha", role: "organizer" },
    { id: "u4", name: "Ananya Desai", role: "organizer" },
    { id: "u5", name: "Ishaan Malhotra", role: "organizer" },
    { id: "u6", name: "Kavya Nair", role: "organizer" },
    { id: "u7", name: "Rohan Gupta", role: "organizer" },
    { id: "u8", name: "Sanya Kapoor", role: "organizer" },
    { id: "u9", name: "Aditya Joshi", role: "organizer" },
    { id: "u14", name: "michael mistead", role: "judge" },
    { id: "u15", name: "Riya Chatterjee", role: "judge" },
    { id: "u16", name: "Devansh Kulkarni", role: "judge" },
    { id: "u17", name: "Amrita Pillai", role: "judge" },
    { id: "u18", name: "Varun Saxena", role: "judge" },
    { id: "u19", name: "Kiara Bose", role: "judge" },
    { id: "u20", name: "Manish Pandey", role: "judge" },
    { id: "u21", name: "Tanya Ghosal", role: "judge" },
    { id: "u22", name: "Pranav Mishra", role: "judge" },
    { id: "u23", name: "Shreya Bhat", role: "judge" },
    { id: "u24", name: "Akash Hegde", role: "judge" },
    { id: "u25", name: "Nisha Agarwal", role: "judge" },
    { id: "u26", name: "Rishabh Chauhan", role: "judge" },
    { id: "u27", name: "Divya Thapar", role: "judge" },
    { id: "u28", name: "Sameer Dsouza", role: "judge" },
    { id: "u44", name: "Abhinav Tiwari", role: "participant" },
    { id: "u45", name: "Sneha Mukherjee", role: "participant" },
    { id: "u46", name: "Vihaan Prabhu", role: "participant" },
    { id: "u47", name: "Dia Lamba", role: "participant" },
    { id: "u48", name: "Sai Krishna", role: "participant" },
    { id: "u49", name: "Tanvi Sawant", role: "participant" },
    { id: "u50", name: "Reyansh Goel", role: "participant" },
    { id: "u51", name: "Ishani Das", role: "participant" },
    { id: "u52", name: "Ayaan Bajwa", role: "participant" },
    { id: "u53", name: "Avni Oberoi", role: "participant" },
    { id: "u54", name: "Vivaan Rathore", role: "participant" },
    { id: "u55", name: "Mehak Chawla", role: "participant" },
    { id: "u56", name: "Atharva Patil", role: "participant" },
    { id: "u57", name: "Sia Bhardwaj", role: "participant" },
    { id: "u58", name: "Dhruv Rastogi", role: "participant" },
    { id: "u59", name: "Kyra Varma", role: "participant" },
    { id: "u60", name: "Arnav Tripathi", role: "participant" },
    { id: "u61", name: "Gauri Mahajan", role: "participant" },
    { id: "u62", name: "Shaurya Dubey", role: "participant" },
    { id: "u63", name: "Shanaya Grover", role: "participant" },
    { id: "u64", name: "Ranveer Sodhi", role: "participant" },
    { id: "u65", name: "Ira Singhal", role: "participant" },
    { id: "u66", name: "Kushal Jain", role: "participant" },
    { id: "u67", name: "Riddhima Sahni", role: "participant" },
    { id: "u68", name: "Pratyush Sinha", role: "participant" },
    { id: "u69", name: "Vanya Ahuja", role: "participant" },
    { id: "u70", name: "Darsh Mistry", role: "participant" },
    { id: "u71", name: "Sara Abraham", role: "participant" },
    { id: "u72", name: "Vedant Parekh", role: "participant" },
    { id: "u73", name: "Zoya Qureshi", role: "participant" },
    { id: "u74", name: "Madhav Gadhavi", role: "participant" },
    { id: "u75", name: "Trisha Roy", role: "participant" },
    { id: "u76", name: "Tejas Shrivastav", role: "participant" },
    { id: "u77", name: "Palak Mittal", role: "participant" },
    { id: "u78", name: "Omkar Deshmukh", role: "participant" },
    { id: "u79", name: "Paridhi Shah", role: "participant" },
    { id: "u80", name: "Lakshya Kalra", role: "participant" },
    { id: "u81", name: "Bhavna Negi", role: "participant" },
    { id: "u82", name: "Tushar Batra", role: "participant" },
    { id: "u83", name: "Himani Kaul", role: "participant" },
];